FROM gcr.io/spiffe-io/spire-server:c8123525fba8943bb084e70317afe32986247424
WORKDIR /opt/spire

RUN mkdir -p data/server
RUN mkdir socket
COPY --from=spire-server-global /opt/spire/bootstrap.pem bootstrap.pem
COPY --from=spire-server-global /opt/spire/conf/server/kubeconfig.yml kubeconfig.yml
EXPOSE 8081
ENTRYPOINT ["bin/spire-server", "run"]
