FROM gcr.io/spiffe-io/spire-agent:c8123525fba8943bb084e70317afe32986247424
WORKDIR /opt/spire

RUN mkdir -p data/agent
COPY --from=spire-server-global /opt/spire/bootstrap.pem bootstrap.pem
ENTRYPOINT ["bin/spire-agent", "run"]
