apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-iid-docs
  namespace: spire
data:
  document: |-
    {
      "devpayProductCodes" : null,
      "marketplaceProductCodes" : null,
      "accountId" : "884177950120",
      "availabilityZone" : "us-west-2b",
      "kernelId" : null,
      "ramdiskId" : null,
      "pendingTime" : "2019-05-13T20:49:30Z",
      "architecture" : "x86_64",
      "privateIp" : "172.31.52.148",
      "version" : "2017-09-30",
      "region" : "us-west-2",
      "imageId" : "ami-061392db613a6357b",
      "billingProducts" : null,
      "instanceId" : "i-0ef8bf0d3cebed88b",
      "instanceType" : "t2.micro"
    }
  signature: |-
    O/PMeHQ/ma8ZC7bMRKfu2xuYnUZ8edK8gxVT3H1xm12zV7FjvFQlCXcnt12SdampEWWnn1eXDXY6Xy7dXY0Wu9kTSC+DcmZ6sdhhawpivispHr5AJXG95wLojp44lmpOqJCX/1DXajXXONHStNXNlHS9jlpuhVFZyJjwsah6Q8g=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-iid-config
  namespace: spire
data:
  default.conf: |
    server {
        listen       127.0.0.1:81;
        server_name  localhost;
    
        location / {
            root   /usr/share/nginx/html;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-agent
  namespace: spire
  labels:
    app: spire-agent
spec:
  selector:
    matchLabels:
      app: spire-agent
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-agent
    spec:
      serviceAccountName: spire-agent
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: ec2-iid-server
          image: nginx:1.15-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: iid-docs
              mountPath: /usr/share/nginx/html
              readOnly: true
        - name: spire-agent
          image: spire-agent
          imagePullPolicy: Never
          volumeMounts:
            - name: agent-config
              mountPath: /opt/spire/conf/agent
              readOnly: true
            - name: agent-data
              mountPath: /opt/spire/data/agent
            - name: socket
              mountPath: /opt/spire/socket
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - --shallow
                - --socketPath
                - socket/workload_api.sock
            failureThreshold: 4
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 3
      volumes:
        - name: nginx-config
          configMap:
            name: agent-iid-config
        - name: iid-docs
          configMap:
            name: agent-iid-docs
        - name: agent-config
          configMap:
            name: agent-config
        - name: agent-data
          hostPath:
            path: /var/run/spire/agent
            type: DirectoryOrCreate
        - name: socket
          hostPath:
            path: /var/run/spire/socket
            type: DirectoryOrCreate
